Part-I Numpy Questions Objective: To build a strong foundation in using NumPy for numerical computations, including creating arrays, performing operations, and leveraging its powerful functionalities.

Task 1: Creating Arrays

Write a Python program to: --> Create a 1D NumPy array of 10 integers ranging from 1 to 10. --> Create a 2D NumPy array of shape (3, 3) with integers from 1 to 9. --> Create a 3D NumPy array with random floating-point numbers of shape (3, 5, 3).
Display the shape, size, and datatype of each array

In [1]:
import numpy as np
ls=np.random.randint(1,11,10)
print(ls.shape)
print(ls.size)
print(type(ls))
ls

(10,)
10
<class 'numpy.ndarray'>


array([5, 7, 5, 3, 5, 8, 8, 4, 3, 1], dtype=int32)

In [2]:
import numpy as np
ls_2=np.random.randint(1,10,9).reshape(3,3)
print(ls_2.size)
print(ls_2.shape)
print(type(ls_2))
ls_2

9
(3, 3)
<class 'numpy.ndarray'>


array([[9, 7, 2],
       [2, 4, 4],
       [2, 8, 3]], dtype=int32)

In [3]:
ls_3=np.random.rand(3,5,3)
print(ls_3.shape)
print(ls_3.size)
print(type(ls_3))
ls_3

(3, 5, 3)
45
<class 'numpy.ndarray'>


array([[[0.62498763, 0.47317476, 0.60135208],
        [0.86956184, 0.88524431, 0.8343826 ],
        [0.9203814 , 0.84851646, 0.99890479],
        [0.17658658, 0.63234057, 0.5030363 ],
        [0.63108877, 0.32135187, 0.17751996]],

       [[0.99678313, 0.48027177, 0.46294185],
        [0.25327851, 0.20118673, 0.42587967],
        [0.50243967, 0.42269548, 0.42774126],
        [0.34390761, 0.30346093, 0.3270707 ],
        [0.87012673, 0.16814263, 0.97902469]],

       [[0.70503328, 0.72733539, 0.58841267],
        [0.18485769, 0.02932075, 0.99104599],
        [0.57600593, 0.61252477, 0.66274733],
        [0.77764034, 0.84994365, 0.97896515],
        [0.08621379, 0.21724842, 0.20749168]]])

Task 2: Array Indexing and Slicing:-

Create a NumPy array from the following list: -->data = [10, 20, 30, 40, 50, 60, 70, 80, 90]
Write a Python program to: -->Retrieve the first three elements of the array. -->Retrieve every alternate element of the array. -->Reverse the array.
Perform the above operations and display the results

In [4]:
data = [10, 20, 30, 40, 50, 60, 70, 80, 90]
ls_4=np.array(data)
print(ls_4[0:3])
print(ls_4[::2])
print(ls_4[::-1])

[10 20 30]
[10 30 50 70 90]
[90 80 70 60 50 40 30 20 10]


Task 3: Mathematical Operations:-

Create two NumPy arrays, A and B, each with 5 random integers between 1 and 20.

Write a Python program to:-

--> Add, subtract, multiply, and divide the two arrays element-wise. --> Compute the dot product of the arrays. 
--> Find the mean, median, standard deviation, and variance o--> array A. --> Identify the maximum and minimum values in array B and their indices

In [5]:
# Add, subtract, multiply, and divide the two arrays element-wise.
import numpy as np
A=np.random.randint(1,20,5)
B=np.random.randint(1,20,5)
print(A)
print(B)
add=A+B
sub=A-B
mul=A*B
div=A/B
print("Addition :",add)
print("Subtraction :",sub)
print("Multiplication :",mul)
print("Division:",div)

[ 2  9 11 10  7]
[ 1 19  1  5 17]
Addition : [ 3 28 12 15 24]
Subtraction : [  1 -10  10   5 -10]
Multiplication : [  2 171  11  50 119]
Division: [ 2.          0.47368421 11.          2.          0.41176471]


In [6]:
# Compute the dot product of the arrays.
A=np.random.randint(1,20,5)
B=np.random.randint(1,20,5)
print(A)
print(B)
dot_product = np.dot(A, B)
print(dot_product)

[14  6  6  4  3]
[7 2 4 6 6]
176


In [7]:
# Find the mean, median, standard deviation, and variance o--> array A.
A=np.random.randint(1,20,5)
B=np.random.randint(1,20,5)
print(A)
print("Mean :",np.mean(A))
print("Median :",np.median(A))
print("Standard deviation :",np.std(A))
print("Varience :",np.var(A))

[ 7 12 12  1  3]
Mean : 7.0
Median : 7.0
Standard deviation : 4.516635916254486
Varience : 20.4


In [8]:
ls_5=np.random.randint(1,12,12)
print(ls_5)
print("2D Array of Size 4X3")
print(ls_5.reshape(4,3))
print("3D Array of Size 2X2X3  ")
print(ls_5.reshape(2,2,3))
print("Transpose of 2D Array and its shape")
print(np.transpose(ls_5.reshape(4,3)).shape)
print("Transpose of 2D Array")
print(np.transpose(ls_5.reshape(4,3)))

[ 5  6 10  1  7  6  9  2  9  3  5  2]
2D Array of Size 4X3
[[ 5  6 10]
 [ 1  7  6]
 [ 9  2  9]
 [ 3  5  2]]
3D Array of Size 2X2X3  
[[[ 5  6 10]
  [ 1  7  6]]

 [[ 9  2  9]
  [ 3  5  2]]]
Transpose of 2D Array and its shape
(3, 4)
Transpose of 2D Array
[[ 5  1  9  3]
 [ 6  7  2  5]
 [10  6  9  2]]


Task 5: Boolean Masking and Filtering:-

Create a NumPy array with 15 random integers between 10 and 50.
Write a Python program to: 

-->Find all elements greater than 25. -->Replace all elements less than 30 with 0. 
-->Count the number of elements divisible by 5.

In [10]:
ls_6=np.random.randint(10,50,15)
print(ls_6)
print("Numbers Greater than 25 :")
print(ls_6[ls_6 > 25])
print("Replacing all elements less than 30 with 0 :")
ls_6[ls_6 < 30]=0
print(ls_6)
print("number of  elements divisible by 5")
print(np.count_nonzero(ls_6 % 5==0))
print("number of nonZero elements divisible by 5")
print(np.count_nonzero(ls_6[ls_6 % 5==0]))

[26 26 20 16 41 48 18 16 24 22 23 39 45 35 13]
Numbers Greater than 25 :
[26 26 41 48 39 45 35]
Replacing all elements less than 30 with 0 :
[ 0  0  0  0 41 48  0  0  0  0  0 39 45 35  0]
number of  elements divisible by 5
12
number of nonZero elements divisible by 5
2



Task 6: Working with Built-in Functions:-

Use NumPy's built-in functions to: 
-->Create an array of 10 equally spaced values between 0 and 1. -->Create an identity matrix of size 4x4. 
-->Generate a 1D array of 20 random integers between 1 and 100, sort it, and find the 5 largest elements.

In [11]:
ls_7=np.linspace(0,1,10)
print("Array of 10 equally spaced values between 0 and 1 \n")
print(ls_7)

Array of 10 equally spaced values between 0 and 1 

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [12]:
print(np.eye(4,dtype="int"))

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [13]:
ls_8=np.random.randint(1,100,20)
print("Original Array :-")
print(ls_8)
print("Sorted Array :-")
print(np.sort(ls_8))
print("5 largest elements")
print(np.sort(ls_8)[-5:][::-1])

Original Array :-
[29 19 94 65 32 22 29  2 58 68 54 48 71 40 51 13 96 20 81 91]
Sorted Array :-
[ 2 13 19 20 22 29 29 32 40 48 51 54 58 65 68 71 81 91 94 96]
5 largest elements
[96 94 91 81 71]


Task 7: Generic:-

Create a Python program that: 
-->Generates two large random arrays of size (100, 100). 
-->Performs matrix multiplication on the two arrays. 
-->Finds the determinant and inverse of the resulting matrix (if possible). 
-->Measures the time taken to complete these operations.

In [14]:
import time

# Step 1: Generate two random 100x100 arrays
A = np.random.rand(100, 100)
B = np.random.rand(100, 100)

# Step 2: Start the timer
start_time = time.time()
print(f"Operation Start time :{start_time} \n")

# Step 3: Matrix multiplication
C = np.dot(A, B)
print("Matrix multiplication completed.\n")
print(C,"\n")


# Step 4: Calculate determinant
det_C = np.linalg.det(C)
print(f"Determinant of the result: {det_C} \n")


# Step 5: Try to calculate inverse if determinant is not zero
if np.isclose(det_C, 0):
    inverse_C = None
    invertible = False
else:
    inverse_C = np.linalg.inv(C)
    invertible = True
    
# Step 6: End the timer
end_time = time.time()
print(f"Operation end time :{end_time} \n")

elapsed_time = end_time - start_time

# Step 7: Print results
print("Matrix is invertible." if invertible else "Matrix is not invertible.")
if invertible:
    print("Inverse matrix calculated successfully.")
    print(inverse_C,"\n")
print(f"Time taken: {elapsed_time:.4f} seconds")

Operation Start time :1753090087.0364754 

Matrix multiplication completed.

[[23.45423047 24.68759986 22.70494983 ... 23.55414596 23.53352209
  21.40439754]
 [24.50128505 25.58268215 24.09019716 ... 25.1567573  26.32131864
  24.38494622]
 [21.18876149 23.06493949 23.36212051 ... 24.4839029  22.7912483
  19.86651115]
 ...
 [25.5624952  25.01570528 26.00251227 ... 25.97865889 25.00179149
  23.73454548]
 [25.8547588  26.36209775 24.15262579 ... 26.5874307  25.98642268
  24.67395193]
 [25.2210993  28.17334039 23.96965738 ... 27.81210021 25.20868251
  23.87595564]] 

Determinant of the result: 2.5608817389127715e+51 

Operation end time :1753090087.4429982 

Matrix is invertible.
Inverse matrix calculated successfully.
[[ 2.00926473 -2.12212466 -1.23988732 ...  1.86960332  0.73105424
   0.80597997]
 [ 3.46196927 -1.40663916 -2.18101426 ...  2.20269046  1.17756772
   0.76835148]
 [-0.94333803  0.39149467  0.3430767  ...  0.78827016 -0.44164315
  -0.41397007]
 ...
 [-4.22012144 -0.21457668  